services:
  mysql:
    image: mysql:9
    restart: unless-stopped
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: cloud-1
  wp:
    image: wordpress:6-fpm-alpine
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - wp-volume:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: cloud-1
  nginx:
    image: nginx:1-alpine
    restart: unless-stopped
    depends_on:
      - mysql
      - wp
    ports:
      - 8080:80
      # - 443:443
    volumes:
      # TODO: rename config file to conf.d or not?
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - wp-volume:/var/www/html

volumes:
  mysql-volume:
  wp-volume:
