services:
  mariadb:
    container_name: ${MARIADB_CONTAINER_NAME}
    build:
      context: ./services/mariaDB
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - cloud-network

  # postgres:
  phpmyadmin:
    container_name: ${PHPMYADMIN_CONTAINER_NAME}
    build:
      context: ./services/phpMyAdmin
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: ${MARIADB_CONTAINER_NAME}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ARBITRARY: 1
    networks:
      - cloud-network
  # wp:
  #   build:
  #     context: ./services/wordpress
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - wp-volume:/var/www/html
  #   environment:
  #     WORDPRESS_DB_HOST: mysql:3306
  #     WORDPRESS_DB_USER: ${MYSQL_USER}
  #     WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
  #     WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
  # nginx:
  #   image: nginx:1-alpine
  #   restart: unless-stopped
  #   depends_on:
  #     - mysql
  #     - wp
  #   ports:
  #     - 8080:80
  #     # - 443:443
  #   volumes:
  #     # TODO: rename config file to conf.d or not?
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - wp-volume:/var/www/html

volumes:
  mariadb_data:
    driver: local
  # wp-volume:

networks:
  cloud-network:
    driver: bridge
