---
- name: Import playbook to uninstall Docker if present on machine
  ansible.builtin.import_playbook: uninstall.yaml

- name: Install and setup Docker
  hosts: ovh
  become: true
  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        update_cache: true
    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "755"
    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r
    - name: Add Docker repository to apt sources
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        filename: docker
    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
    - name: Ensure Docker service is started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

- name: Import playbook to execute post-installation steps
  ansible.builtin.import_playbook: post-install.yaml
...
