---
- name: Configure host machine to work better with Docker
  hosts: ovh
  become: true
  vars:
    docker_group: docker
  tasks:
    - name: Create docker group
      ansible.builtin.group:
        name: "{{ docker_group }}"
    - name: Add user to created group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        append: true
        groups: "{{ docker_group }}"
...
