---
- name: Deploy Docker configuration to machine
  hosts: ovh
  vars_files:
    - vars/app_dir.yaml
  vars:
    dotenv_path: "{{ app_dir }}/.env"
  tasks:
    - name: Synchronize local folder to remote host
      ansible.posix.synchronize:
        src: ../app/
        dest: "{{ app_dir }}"
        rsync_opts:
          - "--chmod=755"
    - name: Copy .env file
      ansible.builtin.copy:
        src: .env
        dest: "{{ dotenv_path }}"
        mode: "644"
    - name: Add domain name variable to .env file
      ansible.builtin.lineinfile:
        path: "{{ dotenv_path }}"
        line: "{{ item }}"
      loop:
        - NGINX_DOMAIN_NAME={{ domain_name }}
        - NGINX_WWW_DOMAIN_NAME=www.{{ domain_name }}
    - name: Start the Docker containers
      ansible.builtin.command:
        cmd: docker compose up -d --build
        chdir: "{{ app_dir }}"
    - name: Ensure all containers are healthy
      ansible.builtin.shell:
        cmd: "[ $(docker ps --format '{% raw %}{{.Status}}{% endraw %}' | grep 'unhealthy' | wc -l) -eq 0 ] && [ $(docker ps --format '{% raw %}{{.Status}}{% endraw %}' | grep 'starting' | wc -l) -eq 0 ] && echo 'All containers healthy' || echo ''"
        chdir: "{{ app_dir }}"
      register: app_status
      until: app_status.stdout != ""
      retries: 10
      delay: 10
...
