- name: run a nginx-wordpress-mysql stack
  hosts: cloud_1
  tasks:
    - name: uninstall conflicting packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
          - docker-compose-v2
          - docker-doc
          - podman-docker
        state: absent
    - name: update cache
      ansible.builtin.apt:
        update_cache: true
    - name: install required packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
    - name: create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755
    - name: download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: a+r
    - name: add repository to Apt sources
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        filename: docker.list
    - name: install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true
    - name: ensure Docker service is started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: copy .env file
      ansible.builtin.copy:
        src: .env
        dest: /.env
